### ISSUE TITLE
Deploy backend to digitalocean

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/realities#110]
* [x] get manual pushing to dokku to work
* [x] automatic pushing with a github action on pushes to master with maybe https://github.com/vitalyliber/dokku-github-action
* [x] enable firewall again
* [x] fix neo4j connection
* [x] remove [frontend-hosting hack](https://github.com/Edgeryders-Participio/realities/blob/988e38455bc333bca37bfa24c2b307070ebbf37f/api/src/index.js#L60-L64) from backend

**Comment by Powersource** [comment]
pushing straight to master :sunglasses: so this issue doesn't have a pr

stuff that's been done so far
* Gustav gave me access to the server
* sort of managing to push stuff to dokku there but the build is failing, even if it's working locally
* config'ed to use a newer node version. was using like 8, now 12 (latest lts)
* moved devdependencies to dependencies in /ui because the heroku stuff was pruning that stuff before we had used it

**Comment by Powersource** [comment]
got past the pruning issue, now getting this

```
-----> Build
       Running build
       
       > realities-app@0.1.0 build /tmp/build
       > npm run build --prefix api && npm run build --prefix ui
       
       
       > realities-api@0.0.2 build /tmp/build/api
       > better-npm-run build
       
       running better-npm-run in /tmp/build/api
       Executing script: build
       
       to be executed: webpack
       Hash: 876dd67abae911cb4133
       Version: webpack 3.12.0
       Time: 2033ms
       Asset     Size  Chunks             Chunk Names
       bundle.js  54.1 kB       0  [emitted]  main
       bundle.js.map    55 kB       0  [emitted]  main
       [0] ./src/graphql/connectors/index.js 10.9 kB {0} [built]
       [1] ./src/db/neo4jDriver.js 309 bytes {0} [built]
       [3] ./src/index.js 2.21 kB {0} [built]
       [13] ./src/graphql/schema.js 258 bytes {0} [built]
       [15] ./src/graphql/typeDefs.js 5.14 kB {0} [built]
       [16] ./src/graphql/resolvers/index.js 9.63 kB {0} [built]
       [21] ./src/graphql/authorization/index.js 463 bytes {0} [built]
       [22] ./src/email/mailService.js 2.42 kB {0} [built]
       [25] ./src/services/scheduler/index.js 321 bytes {0} [built]
       [26] ./src/fetch/loomio.js 3.6 kB {0} [built]
       + 20 hidden modules
       
       > realities-ui@0.1.0 build /tmp/build/ui
       > better-npm-run build
       
       running better-npm-run in /tmp/build/ui
       Executing script: build
       
       to be executed: node scripts/build.js
       Creating an optimized production build...
remote: /tmp/buildpacks/02_buildpack-nodejs/lib/monitor.sh: fork: Cannot allocate memory
remote: Killed
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 137
remote: npm ERR! realities-ui@0.1.0 build: `better-npm-run build`
remote: npm ERR! Exit status 137
remote: npm ERR! 
remote: npm ERR! Failed at the realities-ui@0.1.0 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.4c0Mb/_logs/2020-09-14T14_02_26_502Z-debug.log
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 137
remote: npm ERR! realities-app@0.1.0 build: `npm run build --prefix api && npm run build --prefix ui`
remote: npm ERR! Exit status 137
remote: npm ERR! 
remote: npm ERR! Failed at the realities-app@0.1.0 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.4c0Mb/_logs/2020-09-14T14_02_26_542Z-debug.log
```

**Comment by Powersource** [comment]
So just tried pushing again and now watched htop for ram usage while it's building, and stuff seems to go well until a bit into the build when it gets up to ~910MB (out of 985 available) and then fails with "fork: Cannot allocate memory"

**Comment by Powersource** [comment]
ok upgraded the server to 2GB ram, fixed the error, now getting this:

```
to be executed: node scripts/build.js
       Creating an optimized production build...
       Compiled successfully.
       
       File sizes after gzip:
       
       476.3 KB  build/static/js/main.8650b48a.js
       21.83 KB  build/static/css/main.38cb7ff9.css
       
       The project was built assuming it is hosted at the server root.
       To override this, specify the homepage in your package.json.
       For example, add this to build it for GitHub Pages:
       
       "homepage" : "http://myname.github.io/myapp",
       
       The build folder is ready to be deployed.
       You may serve it with a static server:
       
       npm install -g serve
       serve -s build
       
       
-----> Caching build
       - node_modules
       
-----> Pruning devDependencies
       audited 44 packages in 1.034s
       found 17 vulnerabilities (8 low, 9 high)
       run `npm audit fix` to fix them, or `npm audit` for details
       
-----> Build succeeded!
       
       -----> Change to Node.js build process 
       Heroku has begun executing the "build" script defined in package.json
       during Node.js builds.
       
       Read more: https://devcenter.heroku.com/changelog-items/1573
       
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing realities (dokku/realities:latest)...
-----> Deploying realities (dokku/realities:latest)...
-----> App Procfile file found (/home/dokku/realities/DOKKU_PROCFILE)
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
       DOKKU_SCALE declares scale -> web=1
-----> Attempting pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
185ba27b9f6ffa1b16d9ef0e27ff92185df0c72b7639e8d92ed97cd2fda9965e
remote: App container failed to start!!
=====> realities web container output:
       > realities-api@0.0.2 serve /app/api
       > better-npm-run serve
       running better-npm-run in /app/api
       Executing script: serve
       to be executed: node build/bundle.js 
       /app/api/node_modules/neo4j-driver/lib/internal/util.js:103
           throw new TypeError(objName + ' expected to be string but was: ' + JSON.stringify(obj));
                 ^
       TypeError: Bolt URL expected to be string but was: undefined
           at assertString (/app/api/node_modules/neo4j-driver/lib/internal/util.js:103:11)
           at Object.driver (/app/api/node_modules/neo4j-driver/lib/index.js:244:26)
           at Object.<anonymous> (/app/api/build/webpack:/src/db/neo4jDriver.js:6:21)
           at __webpack_require__ (/app/api/build/webpack:/webpack/bootstrap 876dd67abae911cb4133:19:1)
           at Object.<anonymous> (/app/api/build/webpack:/src/index.js:1:1)
           at Object.<anonymous> (/app/api/build/bundle.js:595:30)
           at __webpack_require__ (/app/api/build/webpack:/webpack/bootstrap 876dd67abae911cb4133:19:1)
           at /app/api/build/webpack:/webpack/bootstrap 876dd67abae911cb4133:62:1
           at Object.<anonymous> (/app/api/build/bundle.js:67:10)
           at Module._compile (internal/modules/cjs/loader.js:1137:30)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! realities-api@0.0.2 serve: `better-npm-run serve`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the realities-api@0.0.2 serve script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2020-09-15T10_48_10_952Z-debug.log
       > realities-api@0.0.2 serve /app/api
       > better-npm-run serve
       running better-npm-run in /app/api
       Executing script: serve
       to be executed: node build/bundle.js 
       /app/api/node_modules/neo4j-driver/lib/internal/util.js:103
           throw new TypeError(objName + ' expected to be string but was: ' + JSON.stringify(obj));
                 ^
       TypeError: Bolt URL expected to be string but was: undefined
           at assertString (/app/api/node_modules/neo4j-driver/lib/internal/util.js:103:11)
           at Object.driver (/app/api/node_modules/neo4j-driver/lib/index.js:244:26)
           at Object.<anonymous> (/app/api/build/webpack:/src/db/neo4jDriver.js:6:21)
           at __webpack_require__ (/app/api/build/webpack:/webpack/bootstrap 876dd67abae911cb4133:19:1)
           at Object.<anonymous> (/app/api/build/webpack:/src/index.js:1:1)
           at Object.<anonymous> (/app/api/build/bundle.js:595:30)
           at __webpack_require__ (/app/api/build/webpack:/webpack/bootstrap 876dd67abae911cb4133:19:1)
           at /app/api/build/webpack:/webpack/bootstrap 876dd67abae911cb4133:62:1
           at Object.<anonymous> (/app/api/build/bundle.js:67:10)
           at Module._compile (internal/modules/cjs/loader.js:1137:30)
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! realities-api@0.0.2 serve: `better-npm-run serve`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the realities-api@0.0.2 serve script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2020-09-15T10_48_15_106Z-debug.log
=====> end realities web container output
```

**Comment by Powersource** [comment]
So we need to install neo4j now in some way. The dokku way of doing it seems to be to use a plugin, but the most recently updated one was last updated in 2016 and is at neo4j 2 (we want 4) https://github.com/creativecodingos/dokku-neo4j-plugin

Maybe just run neo4j directly on the machine and open the ports so realities can communicate outside of docker?

**Comment by Powersource** [comment]
got neo4j started using docker directly. took some notes while doing it:

```
username:

neo4j

password:

<censored, PM me for it or find it in the dokku config vars>

https://hub.docker.com/_/neo4j

ran this to download it:

docker pull neo4j:4.1.1

to run it:

docker run --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data neo4j

set the different needed env vars (url, username, password), something like this:

dokku config:set realities DB_USERNAME=neo4j
```

**Comment by Powersource** [comment]
So so far the Procfile (heroku convention that says what to run to start the service only is

```
web: npm run serve --prefix api
```

which only starts the backend. Idk how they're doing it on the borderland server but it should be enough to use the npm `concurrently` to start both this and use some static file server to launch the frontend

**Comment by Powersource** [comment]
Ook Hugi seems to usually use nginx, which would explain why the procfile looks like this. We just build stuff in dokku but use a docker volume to get the built frontend out of docker, and then serve it with nginx

**Comment by Powersource** [comment]
There seems to be some way of configuring dokku to get it to serve the container using nginx but I can't seem to figure out how :/

**Comment by Powersource** [comment]
So the procfile stuff apparently sets PORT automatically http://dokku.viewdocs.io/dokku~v0.17.9/networking/port-management/#buildpacks which made /api get served on :5000 , :5000 was then forwarded to :50358 which was the port mapping that dokku gave us. So when visiting https://164.90.191.179:50358/ it was just loading for a long while and nothing happened. So I tried manually setting the /api port to something else, because it shouldn't be accessible from the outside https://github.com/Edgeryders-Participio/realities/commit/238a080925cc315cdd2e149b99b14b539a8c7ba2 Then port :5000 was available again and could go into the dokku container and manually serve /app/ui/build using `python3 -m http.server 5000` but when trying that url again it still seems to hang.

**Comment by Powersource** [comment]
Another suspicious thing is that when visiting https://164.90.191.179:50358/ without running the python server it still seems to hang. Is that some odd nginx behaviour or am I ending up at the wrong endpoint?

**Comment by Powersource** [comment]
Yesss some progress! Followed the advice [here](http://dokku.viewdocs.io/dokku/getting-started/troubleshooting/) and disabled the firewall (todo: enable again :p ) and now stuff gets through. Now I just need to find where the build output went, I thought I saw it before but now the dir seems empty...

**Comment by rootux** [comment]
Hmm if it's behind a private network you probably need a NAT 🙂

**Comment by Powersource** [comment]
Was very confused for a bit now. When serving the backend the frontend was made available somehow as well. But then found this

https://github.com/Edgeryders-Participio/realities/blob/988e38455bc333bca37bfa24c2b307070ebbf37f/api/src/index.js#L60-L64

I guess the time that the comment is mentioning is now, so I'll just remove/ignore this behaviour

**Comment by Powersource** [comment]
Now we need to get the deploy to actually be https instead of http to fix https://github.com/Edgeryders-Participio/realities/issues/113

**Comment by Powersource** [comment]
That was pretty easy, now you can, at least technically, log in. You don't get very far though because the only thing the api tells you is that neo4j doesn't work

**Comment by Powersource** [comment]
everything works :ok_hand:
